configs:
  cm:
    #let kustomize use helm and load files outside of their root
    kustomize.buildOptions: "--enable-helm --load-restrictor LoadRestrictionsNone"
    users.anonymous.enabled: "false"
    resource.exclusions: |
      ### Longhorn resources to exclude
      - apiGroups:
        - snapshot.storage.k8s.io
        kinds:
        - VolumeSnapshot
        - VolumeSnapshotContent
        clusters:
        - "*"
      ### Cilium internal resources excluded reduce the number of watched events and UI Clutter
      - apiGroups:
        - cilium.io
        kinds:
        - CiliumIdentity
        - CiliumEndpoint
        - CiliumEndpointSlice
        clusters:
        - "*"
      ### Network resources created by the Kubernetes control plane and excluded to reduce the number of watched events and UI clutter
      - apiGroups:
        - ''
        - discovery.k8s.io
        kinds:
        - Endpoints
        - EndpointSlice
      ### Internal Kubernetes resources excluded reduce the number of watched events
      - apiGroups:
        - coordination.k8s.io
        kinds:
        - Lease
      ### Internal Kubernetes Authz/Authn resources excluded reduce the number of watched events
      - apiGroups:
        - authentication.k8s.io
        - authorization.k8s.io
        kinds:
        - SelfSubjectReview
        - TokenReview
        - LocalSubjectAccessReview
        - SelfSubjectAccessReview
        - SelfSubjectRulesReview
        - SubjectAccessReview
      ### Intermediate Certificate Request excluded reduce the number of watched events
      - apiGroups:
        - certificates.k8s.io
        kinds:
        - CertificateSigningRequest
      - apiGroups:
        - cert-manager.io
        kinds:
        - CertificateRequest
      ### Kyverno intermediate and reporting resources excluded reduce the number of watched events and improve performance
      - apiGroups:
        - kyverno.io
        - reports.kyverno.io
        - wgpolicyk8s.io
        kinds:
        - PolicyReport
        - ClusterPolicyReport
        - EphemeralReport
        - ClusterEphemeralReport
        - AdmissionReport
        - ClusterAdmissionReport
        - BackgroundScanReport
        - ClusterBackgroundScanReport
        - UpdateRequest
    statusbadge.enabled: true
    resource.customizations.health.argoproj.io_Application: |
      hs = {}
      hs.status = "Progressing"
      hs.message = ""
      if obj.status ~= nil then
        if obj.status.health ~= nil then
          hs.status = obj.status.health.status
          if obj.status.health.message ~= nil then
            hs.message = obj.status.health.message
          end
        end
      end
      return hs
  params:
    #traefik will handle encryption
    server.insecure: true
  repositories:
    cryogence-repo:
      name: cryogence
      url: https://github.com/dylanbegin/k8s-apps.git
      type: git
controller:
  replicas: 1
  #resources:
  #  requests:
  #    cpu: 100m
  #    memory: 64Mi
  #  limits:
  #    cpu: 500m
  #    memory: 512Mi
dex:
  enabled: false
redis:
  enabled: true
  #resources:
  #  requests:
  #    cpu: 100m
  #    memory: 64Mi
  #  limits:
  #    cpu: 200m
  #    memory: 128Mi
server:
  replicas: 1
  extraArgs:
    - --insecure
  #resources:
  #  requests:
  #    cpu: 50m
  #    memory: 64Mi
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
  #uncomment this for troubleshooting
  #service:
  #  annotations:
  #    io.cilium/lb-ipam-ips: "10.10.10.111"
  #  type: LoadBalancer
repoServer:
  replicas: 1
  #resources:
  #  requests:
  #    cpu: 10m
  #    memory: 64Mi
  #  limits:
  #    cpu: 50m
  #    memory: 128Mi
applicationSet:
  replicas: 1
  #resources:
  #  requests:
  #    cpu: 100m
  #    memory: 128Mi
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
notifications:
  enabled: false
  #resources:
  #  requests:
  #    cpu: 100m
  #    memory: 128Mi
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
