configs:
  cm:
    #let kustomize use helm and load files outside of their root
    kustomize.buildOptions: "--enable-helm --load-restrictor LoadRestrictionsNone"
    users.anonymous.enabled: "false"
    #we need to exclude cilium and snapshots from being tracked
    resource.exclusion: |
      - apiGroups:
        - snapshot.storage.k8s.io
        kinds:
        - VolumeSnapshot
        - VolumeSnapshotContent
        clusters:
        - "*"
      - apiGroups:
        - cilium.io
        kinds:
        - CiliumIdentity
        clusters:
        - "*"
    statusbadge.enabled: true
    resource.customizations.health.argoproj.io_Application: |
      hs = {}
      hs.status = "Progressing"
      hs.message = ""
      if obj.status ~= nil then
        if obj.status.health ~= nil then
          hs.status = obj.status.health.status
          if obj.status.health.message ~= nil then
            hs.message = obj.status.health.message
          end
        end
      end
      return hs
  params:
    #traefik will handle encryption
    server.insecure: true
  repositories:
    cryogence-repo:
      name: cryogence
      url: https://git.cryogence.net/cryogence/k8s-apps.git
      type: git
controller:
  replicas: 1
  #resources:
  #  requests:
  #    cpu: 100m
  #    memory: 64Mi
  #  limits:
  #    cpu: 500m
  #    memory: 512Mi
dex:
  enabled: true
  #resources:
  #  requests:
  #    cpu: 10m
  #    memory: 32Mi
  #  limits:
  #    cpu: 50m
  #    memory: 64Mi
redis:
  enabled: true
  #resources:
  #  requests:
  #    cpu: 100m
  #    memory: 64Mi
  #  limits:
  #    cpu: 200m
  #    memory: 128Mi
server:
  replicas: 1
  extraArgs:
    - --insecure
  #resources:
  #  requests:
  #    cpu: 50m
  #    memory: 64Mi
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
  #uncomment this for troubleshooting
  #service:
  #  annotations:
  #    io.cilium/lb-ipam-ips: "10.10.10.111"
  #  type: LoadBalancer
repoServer:
  replicas: 1
  #resources:
  #  requests:
  #    cpu: 10m
  #    memory: 64Mi
  #  limits:
  #    cpu: 50m
  #    memory: 128Mi
applicationSet:
  replicas: 1
  #resources:
  #  requests:
  #    cpu: 100m
  #    memory: 128Mi
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
notifications:
  enabled: false
  #resources:
  #  requests:
  #    cpu: 100m
  #    memory: 128Mi
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
