---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peering-policy
spec:
  virtualRouters:
  - localASN: 65002
    exportPodCIDR: false
    neighbors:
     - peerAddress: "10.10.10.1/24"
       peerASN: 65000
       eBGPMultihopTTL: 10
       connectRetryTimeSeconds: 120
       holdTimeSeconds: 90
       keepAliveTimeSeconds: 30
       gracefulRestart:
         enabled: true
         restartTimeSeconds: 120
  # Announce all services
    serviceSelector:
      matchExpressions:
        - {key: somekey, operator: NotIn, values: ['never-used-value']}
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "bgp-lb-pool"
spec:
  blocks:
  - cidr: "10.13.0.0/24" #external ips
