machine:
  kubelet:
    #clusterDNS:
    #  - ${talos-clusterdns}
    extraConfig:
      serverTLSBootstrap: true
    extraArgs:
      rotate-server-certificates: true
  features:
    kubernetesTalosAPIAccess:
      enabled: true
      allowedRoles:
        - os:reader
      allowedKubernetesNamespaces:
        - kube-system
    kubePrism:
      enabled: true
      port: 7445
    hostDNS:
      enabled: false
      forwardKubeDNSToHost: false
  network:
    interfaces:
      - interface: eth0
        dhcp: false
        vip:
          ip: ${talos-vipip}
    kubespan:
      enabled: false
  install:
    image: ${talos-install}
  time:
    servers:
      - ${talos-ntp}
cluster:
  clusterName: ${talos-cluster}
  extraManifests:
    - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
    - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
  network:
    cni:
      name: none
    #podSubnets:
    #  - ${talos-podcidr} #default 10.244.0.0/16
    #serviceSubnets:
    #  - ${talos-svccidr} #default 10.96.0.0/12
  apiServer:
    certSANs:
      - 127.0.0.1 #KubePrism
      - localhost #KubePrism
      - ${talos-vipfqdn}
  proxy:
    disabled: true
