cluster:
    inlineManifests:
        - name: vault-secret
          contents: |-
            ---
            apiVersion: v1
            kind: Namespace
            metadata:
              name: external-secrets
            ---
            apiVersion: v1
            kind: Secret
            metadata:
              namespace: external-secrets
              name: vault-token
            data:
              token: ${vault_token}
            ---
            apiVersion: v1
            kind: Secret
            metadata:
              namespace: external-secrets
              name: vault-ica
            data:
              vault-ica-key: ${vault_ica}
