machine:
  features:
    kubePrism:
      enabled: true
      port: 7445
    hostDNS:
      enabled: false
      forwardKubeDNSToHost: false
  kernel:
    modules:
      - name: nvme_tcp
      - name: vfio_pci
  kubelet:
    extraConfig:
      serverTLSBootstrap: true
    extraArgs:
      rotate-server-certificates: true
    extraMounts: #longhorn storage mounts
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
  network:
    kubespan:
      enabled: false
  install:
    image: ${talos-install}
    disk: /dev/sda #root disk
  sysctls:
    vm.nr_hugepages: "1024"
  time:
    servers:
      - ${talos-ntp}
